chatbothotel/urls.py
from django.contrib import admin
from django.urls import path, include

from chatbot import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='landing'),
    
    # auth
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('guest/', views.guest, name='guest'),
    path('logout/', views.logout, name='logout'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('kamar/', views.kamar, name='kamar'),
    path('profile/', views.profile, name='profile'),
    
    path('chat/', views.chat, name='chat'), #return to view
    path('ajax/kirimPesan1', views.kirimPesan, name='kirimPesan'),
    path('ajax/templateChat/', views.templateChat, name='templateChat'),
    path('ajax/getResponse/', views.getResponse, name='getResponSystem'),

    path('booking/', views.orderKamar, name='booking'),
    path('ajax/get-harga-kamar/<int:kamar>/', views.getHargaKamar, name='hargaKamar'),
    # path("select2/", include(/"django_select2.urls")),
]

chatbot/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class KategoriKamar(models.Model):
    nama = models.CharField(max_length=50)

    class Meta:
        ordering = ['nama']

    def __str__(self) -> str:
        return self.nama

class Fasilitas(models.Model):
    fasilitas = models.TextField()

    class Meta:
        ordering = ['fasilitas']

    def __str__(self) -> str:
        return self.fasilitas
class Kamar(models.Model):
    kategori = models.ForeignKey(KategoriKamar, on_delete=models.CASCADE, null=True)
    nama = models.CharField(max_length=500)
    fasilitas = models.ForeignKey(Fasilitas, on_delete=models.CASCADE, null=True)
    tarif = models.CharField(max_length=50)

    class Meta:
        ordering = ['nama']

    def __str__(self):
        return str(self.nama)

class KategoriPesan(models.Model):
    nama = models.CharField(max_length=50)
    list = models.JSONField(null=True, blank=True)

    class Meta:
        ordering = ['nama']

    def __str__(self) -> str:
        return self.nama

class Respon(models.Model):
    text = models.TextField()
    kategori = models.ForeignKey(KategoriPesan, on_delete=models.CASCADE, null=True)
    kamar = models.ForeignKey(Kamar, on_delete=models.CASCADE, null=True, blank=True)
    token = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ['kamar']

    def __str__(self) -> str:
        return self.text

class Pesan(models.Model):
    text = models.TextField()
    kategori = models.ForeignKey(KategoriPesan, on_delete=models.CASCADE, null=True)
    token = models.JSONField(null=True, blank=True)

    class Meta:
        ordering = ['text']

    def __str__(self) -> str:
        return self.text

class Booking(models.Model):
    total = models.IntegerField()
    tanggal = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['tanggal']

    def __str__(self) -> str:
        return str(self.tanggal)

class DetailBooking(models.Model):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, null=True)
    kamar = models.ForeignKey(Kamar, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['kamar']

    def __str__(self) -> str:
        return str(self.booking.created_at)

chatbot/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models
from django import forms
from django_select2 import forms as select2Form
from .widgets import DatePickerInput, TimePickerInput, DateTimePickerInput

class LoginUserForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}))
    password = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User

        fields = [
            'username',
            'password'
        ]

class CreateUserForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'email'}))
    password1 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control pwstrength', 'type': 'password'}))
    password2 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User

        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]

class KamarWidget(select2Form.ModelSelect2Widget):
    search_fields = [
        "kamar__nama__icontains",
    ]

class kategoriForm(forms.ModelForm):
    class Meta:
        model=models.KategoriKamar
        fields=('nama',)
        labels={
            'nama': 'Kategori Kamar'
        }

    def __init__(self, *args):
        super(kategoriForm, self).__init__(*args)

class bookingForm(forms.ModelForm):
    # tanggal = forms.DateField(widget=DatePickerInput)
    # kamar =
    # kategori = forms.ModelChoiceField(queryset=models.Kamar.objects.filter(kategori=kamar), empty_label='Pilih Kategori Kamar')
    class Meta:
        model=models.Booking
        fields=('tanggal', 'total')
        widgets={
            'tanggal': DatePickerInput,
        }
        labels={
            'tanggal': 'Tanggal Booking',
            'total': 'Total Boking'
        }

    def __init__(self, *args, **kwargs):
        super(bookingForm, self).__init__(*args, **kwargs)
        self.fields['total'].widget.attrs['readonly'] = True
        self.fields['total'].queryset = models.Kamar.objects.none()

class DetailBookingForm(forms.ModelForm):
    fasilitas = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'readonly':'readonly'}))
    class Meta:
        model=models.DetailBooking
        fields=('kamar',)

    def __init__(self, *args, **kwargs):
        super(DetailBookingForm, self).__init__(*args, **kwargs)
        self.fields['kamar'].empty_label = "Pilih Kamar"

class KamarForm(forms.ModelForm):
    class Meta:
        model=models.Kamar
        fields=('nama', 'tarif', 'fasilitas')

    def __init__(self, *args):
        super(KamarForm, self).__init__(*args)
        
class KategoriKamarForm(forms.ModelForm):
    class Meta:
        model=models.KategoriKamar
        fields=('nama',)

    def __init__(self, *args):
        super(KategoriKamarForm, self).__init__(*args)

class ProfileForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}))
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}))
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}))
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'type': 'email'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model=User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password'
        ]

        # def __init__(self, *args, **kwargs):
            # super(ProfileForm, self).__init__(*args, **kwargs)
            # self.fields['password'].empty_label = "Pilih Kamar"

chatbot/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth import update_session_auth_hash
from django.utils.crypto import get_random_string
from django.core.paginator import Paginator
from django.core import serializers
from django.db.models import Q
from django.http import JsonResponse
from django.contrib import messages
from django.core.cache import cache # This is the memcache cache.

from chatbot.models import *
from chatbot.preprocessing import *
# from chatbot.Get_Respon import *
from pprint import pprint
from .forms import *

from chatbot.getRespon import get_response

from nltk.probability import FreqDist

# Create your views here.
def index(request):
    
    konteks = {
        'title': 'landing',
        'subtitle': '',
        'active': 'landing',
    }
    return render(request, 'user/index.html', konteks)

def register(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(
                request, 'Akun ' + user + ' Berhasil dibuat, silakan login untuk melanjutkan', extra_tags='success')
            return redirect('login')

    konteks = {
        'title': 'register',
        'subtitle': '',
        'active': 'register',
        'form': form,
    }
    return render(request, 'registration/register.html', konteks)

def login(request):

    form = LoginUserForm()
    # form = LoginUserForm()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            if user.is_staff:
                return redirect('/admin')
            else:
                return redirect('dashboard')
        else:
            messages.info(request, 'Username atau password salah',
                          extra_tags='danger')

    konteks = {
        'title': 'login',
        'subtitle': '',
        'active': 'login',
        'form': form,
    }
    return render(request, 'registration/login.html', konteks)

def logout(request):
    auth_logout(request)
    return redirect('landing')

def guest(request):
    
    rand = get_random_string(length=3)
    username = 'user'+rand
    user = User.objects.create_user(
            username = username,
            email = username+'@email.com',
            password = make_password('1234678')
        )

    auth_login(request, user)

    return redirect('chat')

@login_required
def dashboard(request):
    kamar = Kamar.objects.all()

    p = Paginator(kamar, 3)
    page = request.GET.get('page')
    objek = p.get_page(page)

    konteks = {
        'title': 'dashboard',
        'subtitle': '',
        'active': 'index',
        'wisata': objek,
    }
    return render(request, 'user/dashboard.html', konteks)

@login_required
def kamar(request):
    kamar = Kamar.objects.all()
    konteks = {
        'title': 'kamar',
        'subtitle': '',
        'active': 'kamar',
        'wisata': kamar,
    }
    return render(request, 'user/kamar.html', konteks)

@login_required
def chat(request):
    # tempat = Tempat.objects.all()
    # template = Respon.objects.filter(kategori=11).values('text');

    konteks = {
        'title': 'chat',
        'subtitle': '',
        'active': 'chat',
        # 'template': list(template),
    }
    return render(request, 'user/chat.html', konteks)

@login_required
def kirimPesan(request):    #noted
    if request.is_ajax and request.method == "POST":
        
        response = 'Success';
        nama = request.POST['nama'];
        text = request.POST['text'];

        respon = get_response(text)

        res = respon

        # res = serializers.serialize('json', respon)

        return JsonResponse({
            "response": response,
            'nama': nama,
            'pesan': text,
            'respon': res,
        })

    return JsonResponse({}, status = 400)

@login_required
def templateChat(request):
    if request.is_ajax and request.method == "GET":
        # template = Respon.objects.filter(kategori=11).values('text');
        data = {
            "response": 'Success',
            "pesan": list(template),
        }
        return JsonResponse(data)
    
    return JsonResponse({}, status = 400)

@login_required
def getResponse(request):
    if request.is_ajax and request.method == "GET":

        respon = Respon.objects.filter(kategori=1).first();
        
        data = {
            "response": 'Success',
            "pesan": respon.text,
        }
        
        return JsonResponse(data)
    
    return JsonResponse({}, status = 400)

@login_required
def orderKamar(request):
    cache.clear()
    booking_form = bookingForm()
    detail_form = DetailBookingForm()

    if request.method == "POST":
        form_booking = bookingForm(request.POST)
        form_detail = DetailBookingForm(request.POST)

        if form_booking.is_valid() and form_detail.is_valid():
            booking = form_booking.save()
            detail = form_detail.save(commit=False)
            detail.booking = booking
            detail.save()
            messages.success(
                request, 'Booking kamar berhasil', extra_tags='success')
            return redirect('kamar')

    konteks = {
        'title': 'booking',
        'subtitle': 'create',
        'active': 'kamar',
        'form_booking': booking_form,
        'form_detail': detail_form,
    }

    return render(request, 'user/booking.html', konteks)

def getHargaKamar(request, kamar):
    if request.is_ajax and request.method == "GET":
        data = Kamar.objects.filter(id=kamar).first()
        
        return JsonResponse({
            # "response": response,
            'tarif': data.tarif,
            'fasilitas': data.fasilitas.fasilitas
        })

    return JsonResponse({}, status = 400)

@login_required
def profile(request):
    if request.method == 'POST' and request.user.is_authenticated:
        user_form = ProfileForm(request.POST, instance=request.user)
        # user_form = UpdateUserForm(request.POST, instance=request.user)
        password = request.POST['password']

        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.password = make_password(password)
            user.save()

            # auth_user = authenticate(request, username=user.username, password=user.password)

            # if user is not None:
            #     auth_login(request, auth_user)

            update_session_auth_hash(request, request.user)
            
            messages.success(request, 'Your profile is updated successfully', extra_tags='success')
            return redirect('profile')
    else:
        form = ProfileForm(instance=request.user)

    konteks = {
        'title': 'profile',
        'subtitle': '',
        'active': 'profil',
        'profileForm': form,
    }
    return render(request, 'user/profil.html', konteks)

chatbot/templates/user/booking.html
{% extends 'basic.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        {% include "alert/message.html" %}
        <div class="card">
            <div class="card-header">
                <h4>Tambah {{title}}</h4>
                <div class="card-header-action">
                    <a href="{% url 'kamar' %}" class="btn btn-danger">Kembali </a>
                </div>
            </div>
            <div class="card-body">
                <form action="#" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4 col-sm-12">
                            {{ form_detail.kamar.errors }}
                            {{ form_detail.kamar|as_crispy_field }}
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <div class="form-group">
                                {{ form_booking.tanggal.errors }}
                                {{ form_booking.tanggal|as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <div class="form-group">
                                {{ form_booking.total.errors }}
                                {{ form_booking.total|as_crispy_field }}
                            </div>  
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_detail.fasilitas.errors }}
                        {{ form_detail.fasilitas|as_crispy_field }}
                    </div>
                    <input type="submit" class="btn btn-primary float-right" value="Tambah Booking">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $('#id_kamar').change(function() {
        var target = $(this).val(); 
        var url = "/ajax/get-harga-kamar/"+target
        console.log(url, target)
        
        $.get(url, function(data) {
            var harga = document.getElementById('id_total');
            var fasilitas = document.getElementById('id_fasilitas');

            harga.value = data.tarif;
            fasilitas.value = data.fasilitas;
        });
    });
</script>
{% endblock %}

chatbot/templates/user/chat.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}
<div class="row align-items-center justify-content-center">
    <div class="col-12 col-sm-12 col-lg-12">
        <div class="card chat-box card-success" id="mychatbox2">
            <div class="card-header">
            <h4>
                <i class="fas fa-circle text-success mr-2" title="Online" data-toggle="tooltip">
                </i> Chat with Bot</h4>
            </div>
            <div class="card-body chat-content"></div>
            <div class="card-footer chat-form">
                <form id="chat-form2" method="POST">
                    {% csrf_token %}
                    {{ form_booking }}
                    <input type="text" class="form-control" name="pesan" id="input-pesan" placeholder="Type a message">
                    <button class="btn btn-primary">
                        <i class="far fa-paper-plane"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    {% comment %} <script src="{% static 'js/page/components-chat-box.js' %}"></script> {% endcomment %}
    <script>

        $(document).ready(function(){
            {% comment %} getTemplate(); {% endcomment %}
        })

        $(document).on('submit', '#chat-form2', function(e){
            e.preventDefault();
            var nama = '{{ user.username }}';
            var text = $('#input-pesan').val();

            if(text.length > 0){
                $.ajax({
                    type: 'POST',
                    url: "{% url 'kirimPesan' %}",
                    data: {
                        nama: nama,
                        text: text,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    },
                    success: function(data){
                        console.log('YES')
                        printUser(data.pesan)
                        printBot(data.respon)
                        $('#input-pesan').val('')
                    },
                    error: function(xhr, textStatus){
                        console.log('NO');
                        {% comment %} console.log(xhr); {% endcomment %}
                    }
                });
            } else {
                alert('Pesan tidak boleh kosong');
            }
        })

        function getResponse(){
            $.ajax({
                type: "GET",
                url: "{% url 'getResponSystem' %}",
                success: function(data){
                    console.log('YES');
                    printBot(data);
                },
                error: function(xhr, textStatus){
                    console.log('NO');
                }
            })
        }

        {% comment %} function getTemplate(){
            $.ajax({
                type: 'GET',
                url: "{% url 'templateChat' %}",
                success: function(data){
                    console.log('YES');
                    printBot(data.pesan, 'template');
                },
                error: function(xhr, textStatus){
                    console.log('NO');
                }
            })
        } {% endcomment %}
        
        function printBot(data, type){
            if(type == 'template') {
                for (pesan in data) {
                    $.chatCtrl('#mychatbox2', {
                        text: data[pesan].text,
                        picture: "{% static 'img/avatar/avatar-5.png' %}",
                        position: 'chat-left'
                    });
                }
            } else {
                var text = $('#input-pesan').val();
                $.chatCtrl('#mychatbox2', {
                    text: data,
                    picture: "{% static 'img/avatar/avatar-5.png' %}",
                    position: 'chat-left'
                });
            }
        }
        
        function printUser(data){
            $.chatCtrl('#mychatbox2', {
                text: data,
                picture: "{% static 'img/avatar/avatar-2.png' %}",
                position: 'chat-right'
            });
        }

    </script>
{% endblock %}

chatbot/templates/user/dashboard.html
{% extends 'basic.html' %}
{% load static %}

{% block css %}

{% endblock css %}


{% block content %}
<div class="row">
    <div class="col-12">
        <div id="carouselExampleIndicators2" class="carousel slide carousel-fade" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators2" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators2" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators2" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100 gallery-more" src="{% static 'img/Hotel-Bintang.jpg' %}" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                  <h5>Hotel dan Resto Bintang</h5>
                  <p>Hotel Bintang adalah hotel dan restoran Bintang Situbondo, hotel Situbondo yang terletak di jalan raya Banyuglugur RT 01 RW 02 kecamatan Banyuglugur, kabupaten Situbondo, Indonesia dengan kode pos 68351. Kelas kamar hotel Bintang Situbondo yakni kamar standar dan kamar superior. Sedangkan harga per kamar mulai dari Rp. 260.000 per malam.</p>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100 gallery-more" src="{% static 'img/unsplash/andre-benz-1214056-unsplash.jpg' %}" alt="Second slide">
                <div class="carousel-caption d-none d-md-block">
                  <h5>Hotel dan Resto Bintang</h5>
                  <p>Hotel Bintang adalah hotel dan restoran Bintang Situbondo, hotel Situbondo yang terletak di jalan raya Banyuglugur RT 01 RW 02 kecamatan Banyuglugur, kabupaten Situbondo, Indonesia dengan kode pos 68351. Kelas kamar hotel Bintang Situbondo yakni kamar standar dan kamar superior. Sedangkan harga per kamar mulai dari Rp. 260.000 per malam.</p>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100 gallery-more" src="{% static 'img/Hotel-Bintang.jpg' %}" alt="Third slide">
                <div class="carousel-caption d-none d-md-block">
                  <h5>Hotel dan Resto Bintang</h5>
                  <p>Hotel Bintang adalah hotel dan restoran Bintang Situbondo, hotel Situbondo yang terletak di jalan raya Banyuglugur RT 01 RW 02 kecamatan Banyuglugur, kabupaten Situbondo, Indonesia dengan kode pos 68351. Kelas kamar hotel Bintang Situbondo yakni kamar standar dan kamar superior. Sedangkan harga per kamar mulai dari Rp. 260.000 per malam.</p>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
{% endblock %}

chatbot/templates/user/index.html
{% extends 'landing.html' %}
{% load static %}
{% block content %}
<div class='row'>
    <div class='col-md-7'>
        <div class="card">
            <div class="card-body">
                <div class='row'>
                    <div class='col-md-12'>
                        <div class="gallery gallery-md">
                            <div class="gallery-item" data-image="{% static 'img/1.jpg' %}" data-title="Image 1"></div>
                            <div class="gallery-item" data-image="{% static 'img/2.jpg' %}" data-title="Image 2"></div>
                            <div class="gallery-item" data-image="{% static 'img/3.jpg' %}" data-title="Image 3"></div>
                            <div class="gallery-item" data-image="{% static 'img/4.jpg' %}" data-title="Image 4"></div>
                            {% comment %} <div class="gallery-item gallery-more" data-image="{% static 'img/1.jpg' %}" data-title="Image 12">
                              <div>+2</div>
                            </div>
                            <div class="gallery-item gallery-hide" data-image="{% static 'img/1.jpg' %}" data-title="Image 9"></div> {% endcomment %}
                        </div>
                    </div>
                </div>
                <div class='row'>
                    <div class='col-md-12'>
                        <p style='font-size: 25px;'><b>Nama : </b>Hotel Bintang</p>
                        <p style='font-size: 25px;'><b>Alamat : </b>Banyuglugur Kabupaten Situbondo Jawa Timur 68359 Indonesia</p>
                        <p style='font-size: 25px;'><b>Vicnity : </b>Banyuglugur</p>
                        <p style='font-size: 25px;'><b>Place Type : </b>Lodging, point_of_interest, establishment</p>
                        <p style='font-size: 25px;'>Hotel Bintang merupakan salah satu rest area di jalur pantura yang dapat menjadi pilihan untuk beristirahat</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='col-md-5'>
        <div class="justify-content-center">
            <h2>Selamat datang di Aplikasi Hotel Bintang </h2>
            <h2>Landing Page</h2>
        </div>
        <div class="d-flex justify-content-center">
            {% comment %} <a href="{% url 'login' %}" class="btn btn-lg btn-primary" style="margin: 15px;">Login</a> {% endcomment %}
            <a href="{% url 'guest' %}" class="btn btn-lg btn-primary" style="margin: 15px;">Live Chat</a>
        </div>
    </div>
</div>
{% endblock %}

chatbot/templates/user/kamar.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}
{% include "alert/message.html" %}
<div class="card">
    <div class="card-header">
        <h4>Daftar {{title}}</h4>
        <div class="card-header-action">
            <a href="{% url 'booking' %}" class="btn btn-primary">Booking Kamar</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped" id="table-kamar">
                <thead>
                    <th>#</th>
                    <th>Nama Kamar</th>
                    {% comment %} <th>Harga</th> {% endcomment %}
                    {% comment %} <th>Fasilitas</th> {% endcomment %}
                </thead>
                <tbody>
                    {% for w in wisata %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ w.nama }}</td>
                        {% comment %} <td>Rp. {{ w.tarif }}</td> {% endcomment %}
                        {% comment %} <td>{{ w.fasilitas.fasilitas }}</td> {% endcomment %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
{% endblock css %}

{% block js %}
<script src="{% static 'plugins/datatables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#table-kamar').DataTable();
    });
</script>
{% endblock %}